#baseURL = 'https://andreapaolo.github.io/fitness4free/'
baseURL = 'https://fitness4free.it'
languageCode = 'it'
title = 'Fitness 4 Free'
theme = "blist"

googleAnalyticsID= "G-2G2TR82Y9Q"
enableRobotsTXT = true

DefaultContentLanguage = "it"
DefaultContentLanguageInSubdir = true
[languages]
    #Italiano
    [languages.it]
    contentDir = "content/it" #Italiano
    weight = 1
    languageName = "Italiano"
    description = "Fitness 4 Free è gratis, non vende schede o servizi di coaching, ti permette di allenarti con i migliori programmi e allenamenti del momento."
    [languages.it.params]
      introTitle = "Fitness 4 Free"
      introSubtitle = "Un nuovo modo di concepire il fitness"
      introPhoto = "/logo.svg"
      frontBundle = "schede"
      #logo = "/logo.svg"
    [[languages.it.menu.main]]
        name = "Il progetto"
        url = "page/progetto/"
        weight = 1
    #[[languages.it.menu.main]]
    #    name = "Schede"
    #    url = "schede"
    #    weight = 2
    #[[languages.it.menu.main]]
    #    name = "Allenamenti"
    #    url = "tags"
    #     weight = 3
    [languages.it.params.homepage.social]
        # Global params common for both languages
        title = "Contattami"
        description = "Se hai delle richieste o vuoi delle informazioni non esitare a contattarmi!"
        #instagram = "https://"
        #youtube=""
        email = "mailto:info@fitness4free.it"

    #English  
    [languages.en]
        contentDir = "content/en" #English
        weight = 1
        languageName = "English"
        description = "Fitness 4 Free is free, doesn't sell workout or coaching services, allows you to train with the best programs and workouts of the moment"
    [languages.en.params]
      introTitle = "Fitness 4 Free"
      introSubtitle = "A new way of thinking about fitness"
      introPhoto = "/logo.svg"
      frontBundle = "training_sheets"
      #logo = "/logo.svg"
    [[languages.en.menu.main]]
        name = "The project"
        url = "page/project/"
        weight = 1
    #[[languages.en.menu.main]]
    #    name = "Training sheets"
    #    url = "training_sheets"
    #    weight = 2
    #[[languages.en.menu.main]]
    #    name = "Workouts"
    #    url = "tags"
    #    weight = 3
    #[[languages.en.menu.main]]
        #name = "Top Post"
        #url = "/en/blog/emoji-support/"
        #weight = 4
        
    [languages.en.params.homepage.social]
        # Global params common for both languages
        title = "Get in touch"
        description = "If you have any requests or want any information, please do not hesitate to contact me!"
        #instagram = "https://"
        #youtube=""
        email = "mailto:info@fitness4free.it"

[params]
    # Enable the darkmode toggle in header
    darkModeToggle = true

    # Enable search in header
    enableSearch = true

    # Custom copyright - optional
    copyright = "Copyright © 2022 - Fitness 4 Free · All rights reserved"
    favicon = "/favicon.svg"

    # Color for the intro details and social links block, not applicable for dark mode
    # Supported values: Any color from TailwindCSS default colors
    # Reference: https://tailwindcss.com/docs/customizing-colors
    ascentColor = "bg-green-50"

    # The page bundle that is shown on the front page
    #frontBundle = "programmi"

    # Used to hide the post metadata such as posted date, reading time and word count
    # Can be used at site level or page level
    hideMeta = true

    # To hide "Other languages" option if the post is available in multiple languages
    # Can be used at site level or page level
    hideOtherLanguages = true

#[params.homepage.social.en]
    # Global params common for both languages
    #title = "Get in touch"
    #description = "I work on everything coding and tweet developer memes"
    #instagram = "https://"
    #youtube=""
    #email = "mailto:info@fitness4free.it"
    

[[menu.main]]
    name = "About"
    url = "/about"

[build]
    writeStats = true

[outputs]
    home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
    [markup.highlight]
        style = "dracula"
    [markup.goldmark.renderer]
        # Enable to include inline HTML
        unsafe = true

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-eval' 'unsafe-inline' www.google-analytics.com www.googletagmanager.com fonts.googleapis.com maxcdn.bootstrapcdn.com fonts.gstatic.com;"
